### ISSUE TITLE
Paura e quattrini un se n'è mai avuti

### ISSUE THREAD

**Issue by sciamp** [unhorsing/ways-of-saying#1]
So I was looking for a translation. I would obviously say "fear" for "paura" and "pennies" for "quattrini".
Still looking for a translation of the ending part though.
Any idea is appreciated.

**Comment by m4ng0** [comment]
What about:
"we never had fear nor pennies" or "we never had fear or pennies"?

**Comment by gpini** [comment]
we never had fear xor pennies?

Il giorno Sab 2 Mag 2015 12:05 Massimo Mangoni notifications@github.com
ha scritto:

**Comment by sciamp** [comment]
If you all agree I would pick "we never had fear nor pennies" and close this issue.

**Comment by m4ng0** [comment]
It's OK for me.
