### ISSUE TITLE
T'hai visto un bel mondo!

### ISSUE THREAD

**Issue by p3lli** [unhorsing/ways-of-saying#104]
"You've seen a beautiful world!"

Honestly, I thought it was already included

**Comment by m4ng0** [comment]
So frequently used that no one thought it was missing in our list.
Well spotted! We wait for a pull request, thanks! :-)

**Comment by gpini** [comment]
Admiring the use of apostrophe in the same place...
What a master's shot!

Il giorno mer 27 set 2017 alle ore 16:40 Massimo Mangoni <
notifications@github.com> ha scritto:
