### ISSUE TITLE
...e compagnia cantante

### ISSUE THREAD

**Issue by p3lli** [unhorsing/ways-of-saying#108]
"...and singing companionship"

**Comment by gpini** [comment]
I know that I'm a bit nerd, but I would suggest  "...and singing fellowship"

Il giorno ven 22 giu 2018 alle ore 16:14 p3lli <notifications@github.com>
ha scritto:

**Comment by p3lli** [comment]
Well... that was my second choice, so "fellowship" be.

**Comment by m4ng0** [comment]
@p3lli, we are waiting for your PR.
