### ISSUE TITLE
Lo sviluppo è fermo?

### ISSUE THREAD

**Issue by tommyblue** [unhorsing/ways-of-saying#119]
Mi rivolgo ai manutentori di questo interessantissimo progetto: lo sviluppo mi sembra un po' fermo, non vorrei che il repo venisse abbandonato 😢

**Comment by m4ng0** [comment]
No, tutt'altro. Incoraggio anche gli altri _maintainer_ a contribuire per validare le varie proposte rimaste aperte tra le _issues_.

**Comment by tommyblue** [comment]
Chiudo sulla fiducia 😆
