### ISSUE TITLE
Alice does Bob a favour...

### ISSUE THREAD

**Issue by m4ng0** [unhorsing/ways-of-saying#15]
- "Grazie mille!"
- "Figurati!"

We could translate it this way:
- "Thank you one thousand!"
- "Picture it!"

Comments are welcome.

**Comment by gpini** [comment]
Do you like "Picture you"?

Il giorno mer 5 ago 2015 alle ore 08:12 Massimo Mangoni <
notifications@github.com> ha scritto:

**Comment by m4ng0** [comment]
Not bad at all!
