### ISSUE TITLE
C'ho capito il giusto

### ISSUE THREAD

**Issue by sciamp** [unhorsing/ways-of-saying#16]
I think "I understood the right" might work.

**Comment by m4ng0** [comment]
Also: 
1. "I understood the proper"
2. "I understood the just"
3. "I understood the fair"
are cool, but I like your version too.

**Comment by gpini** [comment]
In the spirit of the project I also appreciate version 2 by Mango

Il giorno lun 26 ott 2015 alle ore 22:52 Massimo Mangoni <
notifications@github.com> ha scritto:
