### ISSUE TITLE
Non voglio sentire seghe

### ISSUE THREAD

**Issue by m4ng0** [unhorsing/ways-of-saying#2]
Which one would you prefer?
"I don't wanna hear saws" or "I don't wanna hear handj*bs"?
I think the first sounds better.

**Comment by gpini** [comment]
The first one, of course (di corsa)!

Il giorno Mar 5 Mag 2015 19:02 Massimo Mangoni notifications@github.com
ha scritto:

**Comment by sciamp** [comment]
I agree with bova82, I'm pretty sure we already have this one, let me check.
yep [0]

[0] https://github.com/unhorsing/ways-of-saying/blob/master/ways-of-saying#L65

**Comment by m4ng0** [comment]
Perfect! Closing the issue...
