### ISSUE TITLE
Come fosse il giorno del castigo

### ISSUE THREAD

**Issue by gpini** [unhorsing/ways-of-saying#22]
Like it was the Day of Punishment

**Comment by c3s4** [comment]
I like this one so much!!

**Comment by m4ng0** [comment]
I'm a purist, so I prefer "Like it were ..."

**Comment by sciamp** [comment]
+1 "like it were"

**Comment by gpini** [comment]
I propose:
"Like it were the Day of Bunsihment" because the original is "Come fosse il giorno del Gastigo"

**Comment by sciamp** [comment]
@bova82 Bunishment sounds great!

**Comment by m4ng0** [comment]
At first I thought it could have a negative side effect, such as narrow the scope of this project to a regional/local extent. However it is so cool that we cannot lose it.
+1 me too.

**Comment by m4ng0** [comment]
Closed with fcfed495a2693e8c6b67ab5f6bb4d2a82a63f418

**Comment by m4ng0** [comment]
Closed with fcfed495a2693e8c6b67ab5f6bb4d2a82a63f418
