### ISSUE TITLE
tanto va la gatta al lardo che ci lascia lo zampino

### ISSUE THREAD

**Issue by c3s4** [unhorsing/ways-of-saying#27]
so much goes the cat to the lard that she leaves the little paw

**Comment by sciamp** [comment]
love it!

@vivalafiestaaa please provide a pull request

@m4ng0 @bova82 do you like it?

**Comment by c3s4** [comment]
I'm closing this issue because is not a way of sayg but is a proverb.
Sorry

**Comment by gpini** [comment]
We are an open group

**Comment by m4ng0** [comment]
Well, since it is good and we accept proverbs, provided they are not out of scope with this project, I wouldn't be too picky. If you provide a pull request we will merge it for sure!

**Comment by c3s4** [comment]
ok, I'll provide a pull request very soon.
Thank you!!

**Comment by m4ng0** [comment]
Closed with 6098d135a45e3ff5c0c69a461eb503ec30bd329a
