### ISSUE TITLE
Come t'ho fatto ti disfò

### ISSUE THREAD

**Issue by c3s4** [unhorsing/ways-of-saying#28]
I have two proposal here:

"As I made you I'll unmake"

or

"As I done you I'll undo"

**Comment by m4ng0** [comment]
Undo sounds so good that I prefer the second one, with a slight variation: "As I did..."

As a side note, being the first person of the present tense, the title should be "ti disfo" without accent.

**Comment by c3s4** [comment]
Ok, I think "As I did" is the right one.
You are so right about the issue title, without accent is better in this case.

**Comment by sciamp** [comment]
good for me!

**Comment by gpini** [comment]
I propose to use a double "you" as in the original.
"As I did you I'll undo you"

**Comment by c3s4** [comment]
Seems legit!

**Comment by m4ng0** [comment]
Closed with 6098d135a45e3ff5c0c69a461eb503ec30bd329a
