### ISSUE TITLE
Il male voluto non è mai abbastanza

### ISSUE THREAD

**Issue by notthatred** [unhorsing/ways-of-saying#30]
To celebrate my old Grandma's motto I'd like to suggest :

"The evil wanted is never enough"

A meaningful merge of "the evil wanted is never too much" and the "You're never old enough too learn "

**Comment by m4ng0** [comment]
+1
A good contribution, do you want to provide a pull request, or should we include it ourselves?

**Comment by gpini** [comment]
+1 also for me

**Comment by sciamp** [comment]
Love this one!

**Comment by m4ng0** [comment]
Closed by 947c1dd
