### ISSUE TITLE
A occhio e croce

### ISSUE THREAD

**Issue by m4ng0** [unhorsing/ways-of-saying#37]
What about: "By eye and cross"?

**Comment by gpini** [comment]
Nice one!

Il Ven 18 Mar 2016 07:59 Massimo Mangoni notifications@github.com ha
scritto:

**Comment by sciamp** [comment]
cool, i was thinking about "at eye and cross"

**Comment by piccolainne** [comment]
What about "to eye and cross"??

**Comment by gpini** [comment]
This one will never be closed

Il Mar 5 Apr 2016, 17:30 piccolainne notifications@github.com ha scritto:

**Comment by m4ng0** [comment]
I think I'll choose the one by @piccolainne, because "between two quarrelling, the third enjoys" :-D Do you think I should open an issue for this one?
