### ISSUE TITLE
regge l'anima coi denti

### ISSUE THREAD

**Issue by gpini** [unhorsing/ways-of-saying#38]
He/she holds the soul with the teeth
Alternatively:
He/she bears the soul with the teeth

**Comment by c3s4** [comment]
This one is a wonderful one. I prefer the "holds" version.

**Comment by sciamp** [comment]
I like the "holds" version better.

(this one is really awesome dude!)

**Comment by m4ng0** [comment]
A classy one! "Holds" wins for me.
