### ISSUE TITLE
Avere una botta che anche meno

### ISSUE THREAD

**Issue by ottimo** [unhorsing/ways-of-saying#39]
To have a bang that also less

**Comment by m4ng0** [comment]
+1 for me!
Any preference between "bang" and "blow"?

**Comment by gpini** [comment]
+1
I do not have preferences between "bang" and "blow".
Do you like "even less"?

Il giorno mer 23 mar 2016 alle ore 21:15 Massimo Mangoni <
notifications@github.com> ha scritto:
