### ISSUE TITLE
Voglia di lavorare saltami addosso / violentami

### ISSUE THREAD

**Issue by sciamp** [unhorsing/ways-of-saying#4]
So let's add "longing of working jump over me" or maybe "longing of working rape me"?

Which one you like better?

**Comment by m4ng0** [comment]
If you are in a poetic mood, it could be:
"Jump over me, eagerness to work!".

**Comment by sciamp** [comment]
Maybe on instead of over?

**Comment by m4ng0** [comment]
I agree, "on" sounds better.
