### ISSUE TITLE
Chi s'è visto s'è visto

### ISSUE THREAD

**Issue by notthatred** [unhorsing/ways-of-saying#42]
PM Violanti suggests: "Who we've seen, we have seen"

**Comment by m4ng0** [comment]
+1 for me!

**Comment by gpini** [comment]
I could suggest "Who has seen himself has seen himself" but it's too
complicated.
Ok for me

Il giorno mar 5 apr 2016 alle ore 17:20 Massimo Mangoni <
notifications@github.com> ha scritto:

**Comment by m4ng0** [comment]
We are longing for a pull request! :-)
