### ISSUE TITLE
Si fa prima a scavalcarla che a giralle attorno

### ISSUE THREAD

**Issue by p3lli** [unhorsing/ways-of-saying#45]
We do faster to climb over her than to go around her

**Comment by c3s4** [comment]
Awesome!!

**Comment by m4ng0** [comment]
We are waiting for a pull request!

**Comment by ottimo** [comment]
+1

Matteo Rosi
http://about.me/ottimorosi
Il 14 apr 2016 19:14, "Massimo Mangoni" notifications@github.com ha
scritto:

**Comment by p3lli** [comment]
As soon as I manage to solve the "permission denied" issue.

Moreover, I would like to propose:
- "She has seen more ceilings than a painter" (L'ha visto più soffitti di un imbianchino)
- "He has got more horns than a bucket of snails" (L'ha più corna di un cesto di lumache)
- "We ought to make fields out of Grass and grass out of Fields" (Bisognerebbe fare di Prato campi e di Campi prato)

**Comment by m4ng0** [comment]
Closed with 0703e06.
Many thanks to @p3lli.
