### ISSUE TITLE
chi ha pane non ha denti e chi ha denti non ha pane

### ISSUE THREAD

**Issue by piccolainne** [unhorsing/ways-of-saying#47]
What about:

who has bread doesn't have theeth and who has theeth doesn't have bread

?????

**Comment by gpini** [comment]
I don't want to be fastidious but  "who has bread doesn't have _teeth_ and
who has _teeth_ doesn't have bread".
Anyway is ok for me

Il giorno mar 19 apr 2016 alle ore 09:28 piccolainne <
notifications@github.com> ha scritto:

**Comment by piccolainne** [comment]
good point!

Bovazio you are never fastidious <3

**Comment by m4ng0** [comment]
+1
A lot of popular wisdom!

@piccolainne, do you want us to contribute on your behalf or do you prefer sending us a pull request?
