### ISSUE TITLE
Il troppo stroppia

### ISSUE THREAD

**Issue by gpini** [unhorsing/ways-of-saying#49]
The too much stoomuches

**Comment by ottimo** [comment]
+1

On Wed, Apr 27, 2016 at 3:09 PM, Giovanni Pini notifications@github.com
wrote:

> The too much toomuches
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/unhorsing/ways-of-saying/issues/49

## 

[image: --]
Matteo Rosi
[image: https://]about.me/ottimorosi
https://about.me/ottimorosi?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links

**Comment by notthatred** [comment]
I am totally shocked by the beauty of the neologism "stoomuches"

+1 indeed

**Comment by m4ng0** [comment]
OMG!

**Comment by c3s4** [comment]
Please close internet; now!!

**Comment by m4ng0** [comment]
It occurred to me it could be "untoomuches".

**Comment by sciamp** [comment]
holy shit dude! this is awesome!

I also like m4ng0's "untoomuches" to recall the "s" privative function in "stroppia"

**Comment by gpini** [comment]
I'm attached to "stoomuches", even if this is less grammatically correct.
On the other hand untoomuches is universal and more clear.
This is a dilemma.

Il giorno ven 29 apr 2016 alle ore 10:13 Alessandro Campagni <
notifications@github.com> ha scritto:

**Comment by m4ng0** [comment]
Thank you. This issue is closed by d4dca0f286028350c189829e459f759f4b7b3338
