### ISSUE TITLE
È la morte sua

### ISSUE THREAD

**Issue by m4ng0** [unhorsing/ways-of-saying#50]
It's its death

**Comment by gpini** [comment]
This is a very productive day! Approved for me!

Il giorno mer 27 apr 2016 alle ore 17:02 Massimo Mangoni <
notifications@github.com> ha scritto:

**Comment by ottimo** [comment]
+1

On Wed, Apr 27, 2016 at 5:16 PM, Giovanni Pini notifications@github.com
wrote:

> This is a very productive day! Approved for me!
> 
> Il giorno mer 27 apr 2016 alle ore 17:02 Massimo Mangoni <
> notifications@github.com> ha scritto:
> 
> > It's its death
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/unhorsing/ways-of-saying/issues/50
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/unhorsing/ways-of-saying/issues/50#issuecomment-215116590

## 

[image: --]
Matteo Rosi
[image: https://]about.me/ottimorosi
https://about.me/ottimorosi?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links
