### ISSUE TITLE
Non c'è trippa pe' gatti

### ISSUE THREAD

**Issue by c3s4** [unhorsing/ways-of-saying#54]
There's no tripe for cats

**Comment by gpini** [comment]
I would say "an ever green"!

Il giorno lun 2 mag 2016 alle ore 17:04 Davide Cesaroni <
notifications@github.com> ha scritto:

**Comment by m4ng0** [comment]
+1

**Comment by c3s4** [comment]
Can I make a pull request for this one?

**Comment by gpini** [comment]
Please proceed

Il giorno ven 13 mag 2016 alle ore 08:31 Davide Cesaroni <
notifications@github.com> ha scritto:
