### ISSUE TITLE
'un è i'bere, l'è i' ribere!

### ISSUE THREAD

**Issue by p3lli** [unhorsing/ways-of-saying#78]
"It's not the drinking, it's the re-drinking!"

I'm a little surprised by the fact it had not been yet proposed.

**Comment by m4ng0** [comment]
I totally agree, it's a serious lack!

**Comment by gpini** [comment]
Nice one!

Il Dom 19 Mar 2017, 14:13 Massimo Mangoni <notifications@github.com> ha
scritto:

**Comment by m4ng0** [comment]
Closed with #80.
Thank you, @p3lli.
