### ISSUE TITLE
Etuvedrai

### ISSUE THREAD

**Issue by p3lli** [unhorsing/ways-of-saying#81]
Andyouwillsee

**Comment by gpini** [comment]
Se non c'era già è da mettere!

Il giorno gio 20 apr 2017 alle ore 16:59 p3lli <notifications@github.com>
ha scritto:

**Comment by m4ng0** [comment]
I confirm that it is missing and it's certainly a good candidate! We're waiting for a pull request.

**Comment by p3lli** [comment]
Said, done.
