### ISSUE TITLE
Se gl'era bono, 'un si pigliava noi

### ISSUE THREAD

**Issue by p3lli** [unhorsing/ways-of-saying#85]
I don't know if my friends and I managed to get the right conditional sentence for this case.
Please help.

"If he was good, we would have not taken him"

**Comment by m4ng0** [comment]
A very difficult one! But I think we have the skills to get it sorted out...

**Comment by p3lli** [comment]
After a second consulting with my friend, I propose the third conditional:

"If he had been good, we wouldn't have taken him"
