### ISSUE TITLE
Alla cieca

### ISSUE THREAD

**Issue by alexmeia** [unhorsing/ways-of-saying#86]
To the blind woman (improrved version of "to the blind").

**Comment by Gunnegan** [comment]
It seems very improveful.

**Comment by m4ng0** [comment]
Nice and hits the spot. If you issue a pull request, I would consider merging it into master.
What other veterans think about it? @gpini, @sciamp?

**Comment by m4ng0** [comment]
Closed by #87. Thank you @alexmeia!
