### ISSUE TITLE
Non si cava un ragno da un buco

### ISSUE THREAD

**Issue by notthatred** [unhorsing/ways-of-saying#96]
We don't pull a spider from a hole

**Comment by gpini** [comment]
I'd suggest;
"We don't mine a spider form a hole", because "mine" reminds me more a
"cava"

Il giorno lun 7 ago 2017 alle ore 16:40 notthatred <notifications@github.com>
ha scritto:

**Comment by p3lli** [comment]
Bova nailed it

**Comment by m4ng0** [comment]
The original form was suggested by our boss, but @gpini's version embraces this project guidelines.
